config:
    packages:
        -   name: ekyna-media
            location: bundles/ekynamedia/js
            main: player
        -   name: fancytree
            location: bundles/ekynamedia/lib/fancytree
            main: jquery.fancytree
    shim:
        ekyna-media/templates:
            deps: [twig]
        fancybox:
            deps: [jquery]
    paths:
        fancybox: bundles/ekynamedia/lib/fancybox/jquery.fancybox
        videojs: bundles/ekynamedia/lib/videojs/video
        swfobject: bundles/ekynamedia/lib/swfobject/swfobject
    map:
        '*':
            fancybox: ekyna-media/fancybox
        ekyna-media/fancybox:
            fancybox: fancybox
build:
    include:
        - ekyna-media/player
