admin_media:
    resource: 'routing/admin.yaml'
    prefix:   '/%ekyna_admin.routing_prefix%/content'

ekyna_media_download:
    path: /media/download/{key}
    controller: Ekyna\Bundle\MediaBundle\Controller\Media\DownloadController
    methods: [GET]
    requirements:
        key: '[a-z0-9-\./]+'
    options: { expose: true }

ekyna_media_player:
    path: /media/player/{key}
    controller: Ekyna\Bundle\MediaBundle\Controller\Media\PlayerController
    methods: [GET]
    requirements:
        key: '[a-z0-9-\./]+'
    options: { expose: true }

ekyna_media_video:
    path: /media/video/{key}.{_format}
    controller: Ekyna\Bundle\MediaBundle\Controller\Media\VideoController
    methods: [GET]
    requirements:
        key: '[a-z0-9-\./]+'
        _format: mp4|webm|ogg

_liip_imagine:
    resource: '@LiipImagineBundle/Resources/config/routing.yaml'
