ekyna_media_admin:
    resource: "routing/admin.yml"
    prefix:   /admin/content

ekyna_media_download:
    path: /media/download/{key}
    defaults: { _controller: "EkynaMediaBundle:Media:download" }
    methods: [GET]
    requirements:
        key: '[a-z0-9-\./]+'
    options: { expose: true }

ekyna_media_player:
    path: /media/player/{key}
    defaults: { _controller: "EkynaMediaBundle:Media:player" }
    methods: [GET]
    requirements:
        key: '[a-z0-9-\./]+'
    options: { expose: true }

ekyna_media_video:
    path: /media/video/{key}.{_format}
    defaults: { _controller: "EkynaMediaBundle:Media:video" }
    methods: [GET]
    requirements:
        key: '[a-z0-9-\./]+'
        _format: mp4|webm|ogg

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

_oneup_uploader:
    resource: .
    type: uploader
    options: { i18n: false }
