ekyna_media_admin:
    resource: "routing/admin.yml"
    prefix:   /admin/content

ekyna_media_thumb_template:
    path: /media/thumb-template.js
    defaults: { _controller: "EkynaMediaBundle:Media:thumbTemplate" }
    methods: [GET]
    options: { expose: true }

ekyna_media_download:
    path: /media/download/{key}
    defaults: { _controller: "EkynaMediaBundle:Media:download" }
    methods: [GET]
    requirements:
        key: '[a-z0-9-\./]+'
    options: { expose: true }

ekyna_media_player:
    path: /media/player/{key}
    defaults: { _controller: "EkynaMediaBundle:Media:player" }
    methods: [GET]
    requirements:
        key: '[a-z0-9-\./]+'
    options: { expose: true }

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

_oneup_uploader:
    resource: .
    type: uploader
