ekyna_media_media_admin_home:
    path: ""
    defaults: { _controller: "ekyna_media.media.controller:homeAction" }
    methods: [GET]

ekyna_media_media_admin_list:
    path: /list
    defaults: { _controller: "ekyna_media.media.controller:listAction" }
    methods: [GET|POST]

ekyna_media_media_admin_new:
    path: /new
    defaults: { _controller: "ekyna_media.media.controller:newAction" }
    methods: [GET|POST]
    options: { expose: true }

ekyna_media_media_admin_show:
    path: /{mediaId}/show
    defaults: { _controller: "ekyna_media.media.controller:showAction" }
    methods: [GET]
    requirements:
        mediaId: \d+
    options: { expose: true }

ekyna_media_media_admin_tinymce:
    path: /{mediaId}/tinymce
    defaults: { _controller: "ekyna_media.media.controller:tinymceAction", field: description }
    methods: [GET]
    requirements:
        mediaId: \d+

ekyna_media_media_admin_edit:
    path: /{mediaId}/edit
    defaults: { _controller: "ekyna_media.media.controller:editAction" }
    methods: [GET|POST]
    requirements:
        mediaId: \d+
    options: { expose: true }

ekyna_media_media_admin_remove:
    path: /{mediaId}/remove
    defaults: { _controller: "ekyna_media.media.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        mediaId:  \d+
    options: { expose: true }
