ekyna_admin:
    stylesheets:
        - 'bundles/ekynamedia/css/main.css'
        - "bundles/ekynamedia/lib/fancybox/jquery.fancybox.css"
# TODO ?       - "bundles/ekynamedia/lib/fancybox/helpers/jquery.fancybox-buttons.css"
# TODO ?       - "bundles/ekynamedia/lib/fancybox/helpers/jquery.fancybox-thumbs.css"
