ekyna_admin:
    stylesheets:
        - 'bundles/ekynamedia/lib/fancytree/fancytree.css'
        - 'bundles/ekynamedia/lib/fancybox/jquery.fancybox.css'
        - 'bundles/ekynamedia/css/browser.css'
    show:
        templates:
            - EkynaMediaBundle:Show:show_div_layout.html.twig
