ekyna_admin:
    stylesheets:
        - 'bundles/ekynamedia/lib/fancytree/fancytree.css'
        - 'bundles/ekynamedia/lib/fancybox/jquery.fancybox.css'
        - 'bundles/ekynamedia/css/browser.css'
# TODO ?       - "bundles/ekynamedia/lib/fancybox/helpers/jquery.fancybox-buttons.css"
# TODO ?       - "bundles/ekynamedia/lib/fancybox/helpers/jquery.fancybox-thumbs.css"
