# Liip Imagine
liip_imagine:
    resolvers:
        local_media:
            web_path:
                cache_prefix: cache/media
    loaders:
        local_media:
            filesystem:
                data_root: "%kernel.data_dir%/media"
    filter_sets:
        media_front:
            cache: local_media
            data_loader: local_media
            filters:
                thumbnail: { size: [ 800, 600 ], mode: inset }
            post_processors:
                jpegoptim: { strip_all: true, max: "%ekyna_media.image.quality.jpeg%", progressive: true }
                pngquant: { quality: "%ekyna_media.image.quality.png%" }
        media_modal:
            cache: local_media
            data_loader: local_media
            filters:
                thumbnail: { size: [ 800, 600 ], mode: inset }
                background: { size: [ 800, 600 ], color: '#fff' }
            post_processors:
                jpegoptim: { strip_all: true, max: "%ekyna_media.image.quality.jpeg%", progressive: true }
                pngquant: { quality: "%ekyna_media.image.quality.png%" }
        media_table:
            cache: local_media
            data_loader: local_media
            filters:
                thumbnail: { size: [ 24, 24 ], mode: outbound }
            post_processors:
                jpegoptim: { strip_all: true, max: "%ekyna_media.image.quality.jpeg%", progressive: true }
                pngquant: { quality: "%ekyna_media.image.quality.png%" }
        media_thumb:
            cache: local_media
            data_loader: local_media
            filters:
                thumbnail: { size: [ 120, 90 ], mode: inset }
                background: { size: [ 120, 90 ], color: '#ffffff' }
            post_processors:
                jpegoptim: { strip_all: true, max: "%ekyna_media.image.quality.jpeg%", progressive: true }
                pngquant: { quality: "%ekyna_media.image.quality.png%" }
        video_thumb:
            cache: local_media
            data_loader: local_media
            filters:
                thumbnail: { size: [ 120, 90 ], mode: inset }
                background: { size: [ 120, 90 ], color: '#ffffff' }
            post_processors:
                jpegoptim: { strip_all: true, max: "%ekyna_media.image.quality.jpeg%", progressive: true }
                pngquant: { quality: "%ekyna_media.image.quality.png%" }
        video_alt:
            cache: local_media
            data_loader: local_media
            filters:
                relative_resize: { widen: 720 }
            post_processors:
                jpegoptim: { strip_all: true, max: "%ekyna_media.image.quality.jpeg%", progressive: true }
                pngquant: { quality: "%ekyna_media.image.quality.png%" }
