oneup_flysystem:
    adapters:
        local_media:
            local:
                directory: %kernel.root_dir%/../var/media
    filesystems:
        local_media:
            adapter: local_media
            alias: local_media_filesystem
            mount: local_media
