oneup_flysystem:
    adapters:
        local_media:
            local:
                location: "%kernel.data_dir%/media"
        local_video:
            local:
                location: "%kernel.project_dir%/public/%ekyna_media.video.directory%"
    filesystems:
        local_media:
            adapter: local_media
            alias: local_media_filesystem
            mount: local_media
        local_video:
            adapter: local_video
            alias: local_video_filesystem
            mount: local_video
